esm build
UziTech/marked-linkify-it pull request #4
Opened 2021-01-25 21:27 UTC by codeStryke

I've attempted to create an `esm` build, but unfortunately both `marked` and `linkify-it` need to be included in the build because of the current interface.

I'm looking for ideas and suggestions how to make this better.

2021-01-26 00:16 UTC, UziTech commented
Originally I just [copied](https://github.com/UziTech/marked-linkify-it/blob/7ce3866b40358c7a5361ec7adb6ae3fb8a03503a/src/helpers.js) the `inlineText` tokenizer to use it but I changed it to relying on marked. Maybe we just need to go back to copying it so we don't need to bundle marked.

2021-01-26 19:15 UTC, codeStryke commented
I liked your approach since it would mean that any changes to that function would not have to be made twice but I don't see another way either. I've updated the PR, please take a look.

2021-01-26 19:16 UTC, codeStryke commented on package.json
> +    "build": "npm run rollup",
I copied these from [marked](https://github.com/markedjs/marked/blob/master/package.json#L77)

2021-01-26 19:27 UTC, UziTech requested changes
Otherwise LGTM. I'll test it out a little more tonight.

2021-01-26 19:27 UTC, UziTech commented on package.json
> +    "rollup:esm": "rollup -c rollup.config.esm.js"
I think we can simplify this.

```suggestion
    "build": "rollup -c rollup.config.esm.js"
```

2021-01-26 19:42 UTC, codeStryke commented on rollup.config.esm.js
> +import { nodeResolve } from '@rollup/plugin-node-resolve';
do these need to be converted to `require()` syntax?

2021-01-28 21:21 UTC, UziTech approved these changes

2021-01-28 21:23 UTC, merged

2021-01-28 22:11 UTC, codeStryke commented
thank you! 🙏